### ISSUE TITLE
Translations (i18n)

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#13]
I am aware that Lichess uses https://crowdin.com/ for translations, however on that site I could not find a translations page for Lishogi.

**Comment by WandererXII** [comment]
I periodically update lishogi with translations from lichess, since most stuff is the same, although I'm not really sure it's 100% alright to do it like that. I have everything prepared to put unique translations, that are needed only on lishogi on crowdin for translations. I will try to put it there as soon as I can.

**Comment by bebenosuke** [comment]
Hi, how can I contribute to translate specific shogi words? Please let me know once you could prepare lishogi crowdin or lishogi translation files. I will try to translate it.

**Comment by WandererXII** [comment]
@bebenosuke Great! I will let you know after I upload the files on crowdin.

**Comment by kleffa** [comment]
let me be in the same group, I am a latin player so in spanish read Silver for Plata is not the optimal

**Comment by bebenosuke** [comment]
I found lishogi project in crowdin. Let us know once project is ready @WandererXII . Thanks!
https://crowdin.com/project/lishogi

**Comment by justremember** [comment]
Crowdin lishogi project seems to be empty, but apparently you can easily transfer all their translations https://support.crowdin.com/uploading-translations/
