### ISSUE TITLE
Lishogi Bot

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#156]
Hi! I’m new here! Just tried making a lishogi bot after making a bunch of changes in https://github.com/ShailChoksi/lichess-bot . But  i faced a bunch of errors (probably due to my lack of experience). The changes i made allows the bot to play other variants too, but ony if allowed.

If anybody coud help me I’,d be really grateful. Here’s my repo https://github.com/TheYoBots/Lishogi-Bot

**Comment by zzhangb4** [comment]
I've just upgraded lishogi-bot, with account BlazikenBot2000:

2021-01-09 18:21:36,812: Welcome BlazikenBot2000!
2021-01-09 18:21:36,963: Succesfully upgraded to Bot Account!
2021-01-09 18:21:36,964: You're now connected to https://lishogi.org/ and awaiting challenges.
2021-01-09 18:21:39,720: ||| control_queue event: connected
2021-01-09 18:21:39,721: Creating seek for standard

The problems arise after "Creating seek for standard", apparently the seek API is not found. Probably because it hasn't been implemented yet, or else the Bot should not be returning anything. 

Also, I believe some dependencies in your requirments.txt can be avoided, as well as the excessive .yml files (I don't have any experience with fairy-stockfish but I think you can avoid the hassle by just including the executable by itself in /engines/)

**Comment by TheYoBots** [comment]
Thanks a lot @zzhangb4 . I should have mentioned the logs in my first comment itself. Lishogi doesn’t seem to have an api yet is what I understand (and as you said). 

I had even posted this issue in the lishogi official discord, #api-bots-board channel and this is the reply I received from (@) WandererX11 

“Hey, lishogi wasn't tested with bots almost at all, I'll try to thoroughly test it this or the following week.
Some complications you might have noticed are that lishogi backend runs on chess notation.
So it needs uci not usi, chess coordinate system(a1-i9) and promoted pieces are represented by a single character.”
