### ISSUE TITLE
Engine timeout

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#187]
I undeservedly won a game by timeout:
https://lishogi.org/sTkS4wDp

**Comment by justremember** [comment]
Yaneuraou + suisho3 can read this position just fine, so probably not a problem w/ the engine itself.

**Comment by WandererXII** [comment]
Since this should be fixed now(https://github.com/WandererXII/lishogi/commit/befe3f6fd6e1247ddda73c4c7247d2167c38abba), I'm closing this. I originally misunderstood this, I thought that you meant that the ai just refused to play and timed out, not that it timed with time still on the clock, sorry about that. If you notice something like this again, please let me know.

**Comment by ddugovic** [comment]
Sorry; my fault for being so tilted by this that I did poorly reporting the issue.
