### ISSUE TITLE
Bug: Opponent loss on time when player moves exactly time runs out

### ISSUE THREAD

**Issue by Marken-Foo** [WandererXII/lishogi#229]
When I let my time run low and make a move exactly when I run out of time, the game pauses a for a moment then ends with my opponent having lost on time.

https://lishogi.org/Xl7vNa3o/white#49 (first encounter)

Reproducible:
https://lishogi.org/cQ7zcYdK
https://lishogi.org/fmUEXZfR
https://lishogi.org/8J2MOi2s

Maybe not relevant, but games played on mobile browser, Android 9, using Firefox browser 85.1.3.
Move time graph shows the AI taking x seconds for the last move - this is maybe not so correct (it was a short delay in my case at least), and this is also (+-0.1s) the amount of time the AI had left in their main time before I made the "flagging" move.

**Comment by WandererXII** [comment]
Thanks a lot for this. I tried to fix it today, changes are now live on the server. I wasn't able to replicate this after the fixes I made, so I hope I managed to fix this completely. If you can still replicate this, please let me know. I believe the bug was that these moves made right when you ran out of time should have flagged you, but due to a mistake I made, you still received byoyomi time, therefore you weren't flagged, but the clock was internally already stopped, which became apparent after the opponent made the move.

**Comment by Marken-Foo** [comment]
I can't replicate it anymore now after trying a number of games, it seems fixed?
Thanks for the fast fix!
