### ISSUE TITLE
Bug: puzzles with futile interposition

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#265]
A dozen players complained about this sort of thing for an hour yesterday but none of them bothered to record this issue, so I am recording it and attempting to define it.

> Q: What is a "futile interposition"?
> A: Defender may block a check by Rook, Bishop, or Lance by moving a piece or, as stated above, by dropping any piece not already shown. This is known as an "interposition." An interposition is considered futile if the Attacker can simply capture the interposed piece without otherwise changing the solution. Futile interpositions are disallowed.

http://www.shogi.net/nexus/ladder/help.html

Here is an example of a puzzle containing futile interpositions: https://lishogi.org/training/pEUJl

When you consider that shogi attempts to simulate war, and that a captured piece is forced to switch sides, then a king who callously sacrifices his subjects for no benefit is a mad king; futile interpositions are disallowed.

**Comment by WandererXII** [comment]
Okay, I deleted around 300 puzzles with futile interposition and around 200 I 'cut short' before the interposition. I'm sure there will still be many more, but maybe it's better to leave it to the voting system...

**Comment by ddugovic** [comment]
Thanks.  Perhaps also some players who understand this should get their votes multiplied or something.  I'm not opposed to myself doing something coding related to the puzzle importer or something to cut short puzzles where the defender's last move is a drop.

**Comment by WandererXII** [comment]
There is already a system in place that gives different people different number of votes - [PuzzleTrust.scala](https://github.com/WandererXII/lishogi/blob/master/modules/puzzle/src/main/PuzzleTrust.scala). I still haven't given anyone the role 'ROLE_PUZZLE_CURATOR' tho.
I also wrote a script and deleted all tsume puzzles where the solution is to capture a piece that the opponent dropped the last move. So that should be all the futile interpositions.

**Comment by ddugovic** [comment]
Thanks very much!
