### ISSUE TITLE
Uwate/Shitate instead of Gote/Sente for handicap games

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#286]
As suggested by @ddugovic here https://github.com/WandererXII/lishogi/issues/103#issuecomment-826353810.

Gote -> Uwate
Sente -> Shitate

**Comment by peanatsu** [comment]
probably unpopular opinion, but I would go the other way. Stick to simply Black and White in the English version of the site (even replacing Sente and Gote) and leave the Japanese to the Japanese version.

IMHO the English version shouldnt require any knowledge of Japanese. After all, why call them pieces in the preferences, and not koma? Why board instead of shogiban? Why lance instead of kyo-sha?

**Comment by ddugovic** [comment]
Even more unpopular opinion, this should be a language setting:
* English
* Japanese
* Romanized

**Comment by WandererXII** [comment]
Done!
