### ISSUE TITLE
Improper / Incomplete implementation of Impasse/Jishogi draw.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#30]
It needs to be more clear what the precise conditions for declaring a win or draw are for Impasse / Jishogi. Namely, we need to know... 

1. How many points to declare draw (if applicable)? 
2. How many points to declare win?

81Dojo uses the 27 point declaration system so that a draw via Impasse/jishogi is impossible, but this isn't necessary. You could do it the way pros do where there is a draw condition.

In this example game, a draw offer was extended once both kings had entered. However, not enough pieces were entered for the jishogi/impasse condition to apply. Draws by repetition/sennichite and Impasse/Jishogi should be the only legal drawing conditions. Players cannot simply agree to a draw like in chess!

Example game with illegal impasse declaration in end position:
https://lishogi.org/0u8yVOAm#62

Also, I think sennichite/repetition draws should be declared automatically. Then the "draw" could be the impasse declaration.

Furthermore, it helps a lot to know how many points each side has in the event of an Impasse. See the 81Dojo's Impasse calculator for an example.

If you need more references on Impasse, here are some links to reference...
https://en.wikipedia.org/wiki/Shogi#Impasse

The popular app Shogi Wars and 81Dojo uses these conditions for Impasse:

You win the game if you declare and meet the following conditions....

1. Your king is within the 3rd row of your opponent's edge.
2. You possess over 28 points if black and over 27 points if white (a major piece is worth 5 points and a minor piece worth 1 point). Pieces that count for points include the pieces in hand and your own pieces within the 3rd row of your opponent's edge excluding the king.
3. You have over 10 pieces within the 3rd row of your opponent's edge excluding the king.
4. You have over a second of time left.
5. Your king is not in check.

Note: In Shogi Wars, declaration is made automatically. On 81Dojo, Impasse declaration must be made manually.

**Comment by WandererXII** [comment]
This is something I want to really look into, after I fix all the crucial bugs.

Currently it's like this:

- You can offer a draw, once both kings are in opponent's territory. Wiki seems to suggest that's enough, if you think you can mate the opponent you don't have to accept the draw.
> The game reaches an Impasse or Deadlock (持将棋 jishōgi) if both kings have advanced into their respective promotion zones – a situation known as 相入玉 (ai-nyū gyoku "double entering kings") – and neither player can hope to mate the other or to gain any further material.

- Currently you can't win though impasse, which I plan to change in the future. But since wiki says "If an Impasse happens, the winner is decided as follows: each player **agrees** to an Impasse...", I don't think it makes much sense agreeing to your own loss, might as well resign at that point. But maybe I will implement enforcing an impasse...

- Four-fold repetition (same position four times) should result in automatic draw, at least it did when I tested, if it doesn't there has to be some bug.

- Perpetual check four times in a row results in a loss of the player giving the checks.

**Comment by Unferth1968** [comment]
I have a solution to this problem.
It is to adopt a proposal called "Tri-Rule".
The Tri-Rule is that you win if your king moves into the position that his opponent's king was in.

If you are the first player (black) to move your king to a5, you win the game. If you are behind (white), you can win by moving the king to i5. In this case, the only condition is that the king must not be checked.

entering king(入玉) has been criticised by some Japanese shogi fans for being a difficult rule to follow. I would like to propose a simple rule that is easy to work out and easy for people to understand.

**Comment by Tellmarch** [comment]
The 81dojo implementation also matches the official FESA rules (See http://shogi.net/fesa/pdf/FESA%20rules.pdf), I think it would be good to implement it this way.

**Comment by ch-suginami** [comment]
This issue might be one of the most difficult rules of shogi. 
"27-point declaration System" is the official shogi rule for end-game of Jishogi situation, but how many players do know the rule accurately? It would be introduced officially in two or three years ago if I didn't understand incorrectly. I'm worrying about that Jishogi draw rule is so difficult for beginner shogi players that they would stop playing shogi. I want lishogi.org is  one way to start playing shogi with players all over the world. Not only for beginners but also experts can enjoy playing shogi is the best so the lishogi.org is needed to solute this problem as soon as possible before some troubles could occur.

In the above discussions, @Unferth1968 mentioned about "Try-Rule(Tri-rule maybe misspelling, I think)". This rule is easy not only to understand how to win for all players (of course not official rule) but also to make it for developers. Try-Rule is the one of official rules of [Dobutsu-Shogi](https://en.wikipedia.org/wiki/D%C5%8Dbutsu_sh%C5%8Dgi) but only different point is the position to win.

So I will propose one solution of this difficult problem.
1. Introducing Try-Rule until 27-point declaration system will introduced completely and correctly.
2. After setting above two rules, you can select which rules to use for the match. It is one way to separate playing mode for which rules to apply.

This proposal may take hard works for developers but this change will make a good world for on-line shogi players, I think.
I apologize for long sentences and thank for reading.

**Comment by WandererXII** [comment]
Hey thanks a lot. At this point I will implement the try-rule and also start working on the 27-point rule, but that will come later. I will also remove the ability to offer draws.

**Comment by kleffa** [comment]
I think, maybe is simpler block the draw game offer until your king is the oponent camp, then make the points calcuation.
because the entering king is basically "I only can propose a draw game in some conditions" maybe, if you touch the draw offer a pop up with your points to be sure also if the material is so diferent a winner can be declared.

remember in shogi is not allowed offer a draw, and this should be the exeption, so maybe this should be a simple way to resolve this problem, since tri-rule is not a official rule, but a proposal.

Acording to "better moves for better shogi" by Aono Teruichi

"Question = When both sides have entering kings and there is no mate, how is the game decided? Also, please explain at what point the game is stopped.
Answer=When both sides have entering kings and there is no prospect of a mate, adjudication is basically by counting the pieces when all the pieces have entered their respective promotion zones.
... (here is a table where is shown the 
As to the method of stopping the game, if the side with the most pieces has 31 points and if all his pieces are in the promotion zone he can be declared the Winner, or if the side with fewer pieces has 24 points and all his pieces are in the promotion zone a draw can be declared."

**Comment by ddugovic** [comment]
"When both sides have entering kings and there is no prospect of a mate..."

So, when is there no prospect of a mate?

**Comment by WandererXII** [comment]
Done in the last update, if you find any issues with the current implementation, please submit a new issue.
