### ISSUE TITLE
Puzzle "try again" without penalty

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#301]
On Lichess for about 5 years I've unsucessfully lobbied for this feature (which was part of Lichess' original puzzle implementation):
* Moves which are good but not best should not cause a player to fail the puzzle.

In the case of tsumeshogi, this could mean either:
1. A player should be allowed to continue attempting the puzzle until the player cannot checkmate even with the opponent's cooperation (for example, the player is checkmated).
2. A player should be allowed to "try again" without penalty if their move checkmates in the wrong number of moves.

**Comment by WandererXII** [comment]
I don't think lichess really has this problem, since the second best move should be considerably worse that the best move: https://github.com/ornicar/lichess-puzzler/blob/master/generator/generator.py#L46

But I agree with you that this is definitely a problem with tsume on lishogi. While one could argue that longer mates for tsume are wrong and the only correct solution is the shortest mate, I don't think it's optimal.

While I like your idea of letting the player continue even with wrong moves, I think there would still be problems with that:

- What moves would the opponent play to moves made by the player - currently puzzle provides a string with a correct sequence of moves, we can't provide response to every move the player could make. Therefore the move response would either have to be a random move or a result of local analysis. The former would result into meaningless positions and the latter is not reasonable at all, since not all devices support wasmx and we also can't really expect people to run engines on phones for instance.
- Letting players play until they get checkmated could turn into hundreds of moves, which I believe is not the best. Players wouldn't be sure when to quit the puzzle and we would force them into basically resigning the puzzle, which I believe makes it much worse experience. One solution to this could be to limit it to X additional moves instead.

But I was thinking of solving this by removing all puzzles where the second best move also leads to mate or perhaps where the second mate is shorter than the best mate + X (since something like mate in 19 for tsume that is supposed to be mate in 3 seems just wrong). This would make it much harder to find longer tsume problems, but I think it's necessary. Not sure how large the X should, though.

**Comment by ddugovic** [comment]
Yeah... it's hard to do better than your suggestion, and most puzzles I've seen seem to follow it.

* It would be cost-prohibitive, but a full game would be played against the AI.  (Alternatively, under the current system a player could flag/challenge a puzzle and if they defeat the AI at its highest level, recoup lost puzzle rating points.)
* Players would likely resign as soon as they obtain a lost position, but you're right that a "limit it to X additional moves" sounds fair too.

**Comment by justremember** [comment]
I have a proposed workaround for tsumes with longer solutions. It will take some modifications with both the puzzle generator and lishogi backend.
Let's take this yaneuraou puzzle as an example: https://lishogi.org/analysis/standard/l5s1l/6gb1/2%2BR2p1pn/pns1p1p1p/2kp2P2/1p1P1SR1P/P1G1PP3/9/4KG1NL_b_BSNL2Pg2p_1#0
![image](https://user-images.githubusercontent.com/14817065/118267107-202d7c00-b4ee-11eb-88c3-702281e2a967.png)
In this branch, 64B is the correct move, 53B, 76S, 76L, 67N lead to longer mates. The puzzle generator will simply take note of the inferior but still mating moves. The puzzle interface will then allow the user to try again if they made one of the longer mating moves.
![image](https://user-images.githubusercontent.com/14817065/118267449-aea1fd80-b4ee-11eb-8281-3059f047eb8f.png)
Here, we just played 64B 85K. 86G is the correct move, but there are other longer mating moves as well, which the puzzle generator would also log and gets sent to lishogi. Same story with the user interface (try again if user makes a longer mating move).
So instead of just storing a sequence of moves (64B 85K 86G), the puzzle generator will also include those alternate moves. No need to go deeper on those moves, since the user doesn't get to explore them anyway in the puzzle view.
![image](https://user-images.githubusercontent.com/14817065/118268426-f412fa80-b4ef-11eb-9f57-e483e1863466.png)
This is how each puzzle would look like. I understand it might take longer in terms of development time & computing resources, but right now it's the only way I see to solve this problem without making it hard on the user's device.

**Comment by justremember** [comment]
However If you are going the X route I think X=6 is already good enough. If the puzzle says "mate in 7" hopefully no one will be able to see a mate in 13...

**Comment by WandererXII** [comment]
> It would be cost-prohibitive, but a full game would be played against the AI. (Alternatively, under the current system a player could flag/challenge a puzzle and if they defeat the AI at its highest level, recoup lost puzzle rating points.)

Hmm, server side analysis... But I don't think turning puzzles into games against AI would make it a good experience, maybe a separate mode, since I agree it can be very beneficial, but I feel like puzzles should have an immediate right/wrong answer (or at least 'wrong, but you can try again').

@justremember 
I really like that. The only hard thing implementation-wise about it seems to be the reevaluation of the puzzles with larger multipv and keeping track of the alternative moves, since I remember multipv betraying me on some occasions. This would also work with storm and streak for later.

> But I doubt more than 5% of yaneuraou puzzles will remain after this filtering.

I tried running it yesterday marking all puzzles where the second best move is also checkmate (no matter how slow). Out of current 4082 tsume puzzles, 3167 would need to be removed. If we allowed X=10 (second mate is at least +10 longer accounting for interposition), we would need to delete (3167 - 110) puzzles.
That might seem like a lot, but I believe I could replace these in a week's time (or two weeks'). With this I would also like to get rid of the 'Mate in X' hint that is present with tsume puzzles.
New tsume puzzles would then be generated with something like this:

```
def is_ambiguous(povscores, winner):
    if len(povscores) == 1:
        return False
    best_score = povscores[0]['score'].pov(winner)
    second_score = povscores[1]['score'].pov(winner)
    if best_score.is_mate():
        if second_score.is_mate() or win_chances(second_score) > 0.8:
            return True
        return False
    return True
```

I'm not sure what's better now. Having only one correct solution seems a bit cleaner to me, probably just my bias.
With the 'try again' option we could theoretically have more puzzles, which is nice. But one worry I have is that we would just shift the problem back, now instead of what's the correct solution, we would be arguing what's a good enough alternative move (having to explain that only mates to X depth are considered valid alternative moves, making it a tiny bit more confusing for everyone to uderstand). Also the puzzles would be considerably easier with this...

**Comment by justremember** [comment]
> I tried running it yesterday marking all puzzles where the second best move is also checkmate (no matter how slow).
So you checked for every move in the solution right, not just the first move? Like in a 7te, if the 3rd or 5th move has multiple possible solutions leading up to mate, not just 1st move. For the very last move I think we can theoretically allow multiple solutions, if shogiground itself can detect checkmate.

**Comment by WandererXII** [comment]
> if shogiground itself can detect checkmate.

shogiops can, even currently if you find mate it immediately throws 'puzzle solved' - https://github.com/WandererXII/lishogi/blob/master/ui/puzzle/src/moveTest.ts#L38.

> So you checked for every move in the solution right, not just the first move? Like in a 7te, if the 3rd or 5th move has multiple possible solutions leading up to mate, not just 1st move. ... About the is_ambiguous function shouldn't this be recursive? So it checks for all moves. Like this ... (unless you are iterating is_ambiguous over all moves already)

Yep checked every move, something like this:

```
    while not game.is_game_over():
        povscores = engine.analyze(game.sfen(), Limit(depth=18))
        if game.turn == winner and is_ambiguous(povscores, winner):
            break
        best_move = get_best_move(povscores)
        game.push(best_move)
```

I also tried finding the slower mates to do what you suggested, but Fairy (Yaneuraou crashes on tsume that don't have almost all pieces) had trouble finding mates 10+ with larger multiPV, unless I set higher depth (which was therefore much slower), giving it less memory, somehow made the results a bit better, but still somewhat random and sometimes it also just seemed to hang. At least for now I think it's better to go with deleting the puzzles with slower mates.
