### ISSUE TITLE
Making video from Kifu

### ISSUE THREAD

**Issue by SharkCacao** [WandererXII/lishogi#350]
Hello, I haven't made any request in this github, it is my first time.
And I'm not native English speaker, so this request will be very poorly written.
But I would really appreciate it if you read this, and of course, I would REALLY appreciate it if you make up this function.

I have been making videos of my shogi games, but it is hard to record every game.
Also, video data takes up a lot of space in my PC, and sometimes I forget to record.

So, I would like lishogi to have a function to replay the past games in lishogi, "**based on the time spent for each move.**"
Otherwise, it would be great to have a function to make a movie of the game from Kifu files, which record the moves and the time consumed for each move.
This feature would be a great help to video editors, as they would not have to record every time.
Thank you very much.

**Comment by WandererXII** [comment]
Hello, something similar is planned. Not video but gif (example from lichess - [https://lichess1.org/game/export/gif/7IDyGBe7.gif]()). This is the source code that needs to be modified [https://github.com/niklasf/lila-gif](). I plan to rewrite that for lishogi hopefully soon.
Your idea to replay a game with correct move times seems interesting. But only use case I can see is recording a game you didn't get to record before, otherwise it seems better to just scroll through the moves at your own pace. Thanks.

**Comment by Marken-Foo** [comment]
There is already a way to replay the game in real time. At the game analysis board after the game, press the hamburger icon at the bottom right (the one that looks like a 「三」character), scroll down, and select "Real time" under replay mode.

![image](https://user-images.githubusercontent.com/41288521/122341386-fe546880-cf75-11eb-8c1c-2655fb35270b.png)

**Comment by SharkCacao** [comment]
Thank you for your prompt replies, and sorry for my lacking of searching for Github.
I will try making video from this function. Thank you so much.
