### ISSUE TITLE
Puzzles: show source after puzzle solved/failed

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#367]
The source is a large hint towards solving the puzzle. If yaneuraou, then it's a mate in 3, 5 or 7. If a lishogi game is a source it could also be a tactic, but rarely a mate. Other sources blantantly give out the # of moves. Therefore I suggest hiding the source until the user fails or solves the puzzle.

On another note I read on twitter people want more non-mate puzzles, because the shogi community has tsumeshogi in abundance already.

**Comment by WandererXII** [comment]
Puzzles from games will always be recognizable tho, because they got the opponent's move.

> On another note I read on twitter people want more non-mate puzzles, because the shogi community has tsumeshogi in abundance already.

The only place we can get non-mate puzzles from in larger volume is probably from lishogi games. I got 2k of those ready, I plan to analyse more.
I also got another cca 10k yaneuraou puzzles, what do you think about them quality-wise? Should I analyse more (2mil candidates left, will result in something like 8k prob) or should I try to look for other sources.

**Comment by justremember** [comment]
With current filtering, yaneuraou mate puzzles are of good enough quality already IMO. Though I can imagine people wanting more balance between mate and non-mate puzzles in mixed training. Cause right now there's around 90% chance that a tsume will appear in https://lishogi.org/training/mix.

**Comment by WandererXII** [comment]
> With current filtering, yaneuraou mate puzzles are of good enough quality already IMO. Though I can imagine people wanting more balance between mate and non-mate puzzles in mixed training. Cause right now there's around 90% chance that a tsume will appear in https://lishogi.org/training/mix.

Meaning more puzzles from games, I will work on a new batch.


Original issues solved with #367
