### ISSUE TITLE
Why are most tournaments chess time control

### ISSUE THREAD

**Issue by Little-Mage** [WandererXII/lishogi#439]
Why is the time control of most tournaments chess time control instead of byoyomi?

**Comment by WandererXII** [comment]
Mostly because it would mean lowering the initial time significantly, since 1 or 2 second byo is almost useless (but chess increment with small values is still noticeable). So in order to do something like 10 byo, we would need to more than halve the initial time, and then we would need to figure out what to do with berserk...

But I am open to changing that...
https://github.com/WandererXII/lishogi/blob/master/modules/tournament/src/main/Schedule.scala#L309
- TC(initial, increment, byoyomi, periods), if you want to suggest different time control

**Comment by ddugovic** [comment]
The tournament schedule is more balanced now #531 .
