### ISSUE TITLE
[Bug] Study from SFEN, move numbering for gote off by one

### ISSUE THREAD

**Issue by Marken-Foo** [WandererXII/lishogi#460]
When creating a study chapter with gote to move, the move numbering is off by one in the movelist.

e.g. creating a chapter from the SFEN `lnsgkgsnl/1r5b1/ppppppppp/9/9/2P6/PP1PPPPPP/1B5R1/LNSGKGSNL w - 2` and making a move with gote shows in the move list e.g. 1. P84 instead of 2. P84.

**Comment by WandererXII** [comment]
Currently the move number is dependent on ply, which is dependent on color. Meaning if it's gote to move, the ply has to be odd and move number even (offset by 1).
In order to have handicaps start at 1 and not at 2, the frontend 'fakes' it, that if the initial position started with gote to move, it decreases all move numbers by 1, that's the behavior you observe - definitely not ideal. We will just have to keep move number separately, I will get on it.
