### ISSUE TITLE
change coordinates to top of board

### ISSUE THREAD

**Issue by kleffa** [WandererXII/lishogi#48]
traditionaly, coordinates are shown in the top border of board also option to hide coordinates should be interestint to add

**Comment by WandererXII** [comment]
I will consider it, hopefully it won't screw up the layout too much.
But if you want to hide the coordinates you can - go to preferences and under "Board coordinates" select "no".

**Comment by timezombi** [comment]
Alternatively, it might also be worth considering having the file/column coordinates on the bottom if viewing from gote's perspective and on the top from sente's perspective. For me at least, when trying to count squares, I will naturally try to focus my gaze on the first rank and mentally count up.

Currently, when viewing from sente's perspective it is a bit difficult since I will focus on the top first and be unable to see the file coordinates at all within my field of view!

**Comment by WandererXII** [comment]
Coordinates are now on top, I think I will change them somehow in the future so there are better visible on phones, not sure how tho...

**Comment by kleffa** [comment]
They work, in mobile, maybe the rank ones to bottom to make them more
armonic
