### ISSUE TITLE
Request for pocket repositioning

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#569]
With the new awesome update to Shogiground where you can interact with the pockets, I think the next logical step would be to have the pockets closer aligned with the board as in real life piece stands, rather than off to the side on a separate panel. I made a mockup of how this could look (from the older version, so the pockets don't have the same background):

![image](https://user-images.githubusercontent.com/52322435/184878835-fa2740a4-c96b-4892-92b2-75344801aff8.png)

Just imagine that the pieces are also facing the standard direction (was too lazy to rotate each piece in Photoshop). The right panel that contains the movelist would have to be a bit narrower to accommodate, but there's still plenty of room. It would also now have room to be taller as well (which is not in the mockup).

This would also be very helpful for streamers, so that they can make their streaming window more compact.

Is this something feasible?

**Comment by WandererXII** [comment]
I was considering something similar. Ideally I would like to make the piece stands similar to their real life version. Something like this:
![image](https://user-images.githubusercontent.com/43043181/184896934-27f6f5d2-ba1f-4c72-9b94-47148f1d69e1.png)
But that would require a lot of repositioning of other elements on the page, changing the layout completely. And for streamers - this would just make it worse for them...
Your proposal seems nice, the board is taller than wider, so that created some space on the sides, and the moves are unnecessarily wide anyways, so making it narrower wouldn't hurt.
But this would be a big change for users, I don't want to support two different versions of the layout, since it makes testing any change take more time, but maybe it's worth it.
Lichess did a streamer layout (https://lichess.org/forum/general-chess-discussion/streamer-lichess-layout)... Maybe also something worth considering.

**Comment by CouchTomato87** [comment]
Hmmm... I think if you were to do it with square piece stands, you'd have to effectively split up the whole "move list" panel into separate pieces to make optimal use of space. For example, putting the player names and their time in the currently empty top right and bottom left spaces. Then that just leaves the move list and resign options. Unfortunately, I don't think it can be narrowed much because of all the control buttons, but what if it was instead super widened and placed *below* the board?

**Comment by WandererXII** [comment]
Yep, it was just something I was considering, another problem with the classical square stands I mentioned would be that lishogi has three layouts - 1 column (phone), 2 columns, 3 columns (most desktops). 1 column would obviously stay as it is now, since that seems optimal, but 2 columns would just need to be reworked/removed.

But I really like your proposal, it would make a lot of things easier - hands would be in the same grid area as the board and it would also solve the annoying tiny hands pieces when the board is scaled up too much.
![image](https://user-images.githubusercontent.com/43043181/186780747-10b8bf02-98ab-465d-a563-f84e9c118f8a.png)
So I will try it and add an option to preferences in the next update, something like _Compact | Standard_ layout, and if it's well received, I will probably make it the default. I don't want to keep two layouts around, but removing the current one right away is probably a bit rushed, so we'll see.

**Comment by WandererXII** [comment]
Done!
