### ISSUE TITLE
Custom Board theme opacity control confusion

### ISSUE THREAD

**Issue by killerducky** [WandererXII/lishogi#574]
It took me a long time to realize the opacity of the board background color defaults to 0%. Until I changed that it looked like my color was not being used at all. Not sure exactly how to fix this, maybe label the opacity controller? I saw the slider but ignored it while trying to get the color to work.

If you default it to 100% opaque I guess that would cover custom background images? Then it could be the same problem for people trying to use a background image. Maybe default to 50% opacity? I guess in that case most people will then have to change it to 0% or 100%. So maybe there isn't a good default. 

Anyone else have some idea for this?

**Comment by WandererXII** [comment]
Yep, I completely agree. I tried to remedy this by making the alpha slider _flash_ red, when color is being changed and alpha slider is still at 0. Maybe I should add more effects to make it more visible. I want the defaults to be transparent boards, since that will simply work on all backgrounds (dark/white/transparent), but I could change it.
![fT](https://user-images.githubusercontent.com/43043181/185092442-098626d1-5c70-46b9-8731-ffd638dc3f4b.gif)

**Comment by WandererXII** [comment]
The slider now glows a bit _harder_. And after few seconds, if the user still hasn't noticed and changed the alpha slider position, an arrow will appear.
![fT2](https://user-images.githubusercontent.com/43043181/185663977-46f4f691-c46e-4987-b27e-9fce21c440cc.gif)
I think this should be good enough for people to notice why the color isn't changing. Other option we have is to change the default bg color to some color with 100 opacity, but I would prefer to keep the default transparent. I will keep this open for now.

**Comment by WandererXII** [comment]
I will probably change the default to something with 100% opacity, that seems more reasonable as a default, I'm considering white board color with black grid for dark theme and the opposite for light theme...

**Comment by WandererXII** [comment]
Changed the default to have at least some opacity.
