### ISSUE TITLE
Suggestion: NN engine like yaneuraou + orqha/elmo as server bot

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#66]
Right now, fairy stockfish is much weaker than current NNs. It would be nice to play against a decent bot (and in the future, have it analyze my games from the site itself). But the main concern I think is how NNs are currently resource intensive. An NN with less resources could still be stronger than fairy though.

This is a docker setup that installs yaneuraou + orqha/elmo alongside shogigui, could help: https://github.com/jruffet/docker-shogigui

**Comment by kleffa** [comment]
Please consider this as a priority

**Comment by WandererXII** [comment]
There was a bug in the configuration of the current's bot difficulty, causing it to play below what it could. That should be fixed since yesterday. Did you notice improvements in the difficulty?

**Comment by justremember** [comment]
Haven't tested it myself but Illya, a 1 dan in 81dojo, just beat AI level 8 an hour ago. https://lishogi.org/p38HB5gU

**Comment by ianfab** [comment]
You can also play against it on https://www.pychess.org/ to compare. The difficulty settings there should be identical, so if the actual playing strength differs, there might be something off with the settings. Normally, level 8 should be very tough for a 1 dan (speaking as a 1 kyu FESA myself). Someone rated ~2000 on 81dojo also played dozens of games against it on pychess and he only won a few of them.

**Comment by kleffa** [comment]
I guess set up a engine is not just to play against it, also to analize
games, there it should be a very good one.
By now If I want to analize with computer a chess game I have just one
click in lichess, but in 81dojo I have to export kifu, set up shogiGui and
import there, as my PC is old, I can't support yanegura OU, other options
is use kento, but everything is more and more steps.
Sadly stockfish is not a profesional shogi player to help me to improve, I
tried several times and just can say it is like play against a shogi game
for a old Nintendo.

**Comment by ianfab** [comment]
Sure, switching to a stronger engine of course makes sense (especially for saving server resources), and I am by no means arguing against that, but just providing input to identify potential issues with the settings which can still be useful until the switch will eventually be done.

From my point of view the following points might be relevant for this topic:
* Probably the easiest part to implement should be to just exchange the binaries used in fishnet. Since most strong shogi engines are also based on Stockfish, they usually also have the `Skill Level` parameter and use the USI protocol, so using a different engine for (not yet available) server-side analysis as well as game play should be relatively easy.
* I am currently not aware of any other WASM port of a shogi engine, so it might be harder to find a better replacement for client side analysis. However, as soon as server-side analysis will be there, that might be less of a concern.
* I do not know if shogi variant (e.g., dobutsu, mini, kyoto, judkins, goro-goro, etc.) support is planned for lishogi, but if so, Fairy-SF might still come in handy again at a later point for server-side analysis, because to my knowledge most other shogi engines exclusively support 9x9 shogi.

**Comment by kleffa** [comment]
https://lishogi.org/U2K2pvvp/black if I can win against SF level 8, it is not strong, Im a kyu level player (seeking for shodan)

**Comment by IanOsgood** [comment]
Does anyone know what the engine is behind the computer player of PlayShogi.com?  It is very fast and very strong, stronger than Bonanza on my local machine.

The current LiChess computer player is doing the community a disservice, as it is not demonstrating good shape or joseki at all.

**Comment by justremember** [comment]
Pretty sure it's yaneuraou + elmo. Having fairy stockfish for local evaluation is better than none at all, it can detect mates and tactics, but I believe users should be made aware its materialistic, lacks an eye on strategy, and is weaker than the strongest amateurs.

**Comment by justremember** [comment]
If yaneuraou does get implemented, I think having more levels than just 8 is appropriate. Maybe 20.

**Comment by WandererXII** [comment]
https://lishogi.org/blog/X_efbxEAACAAVHnP/yaneuraou---play-with-the-computer
