### ISSUE TITLE
Indicating variant in kif

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#666]
Let's take minishogi as an example, for starting position we have this:
```
手合割：5五将棋
先手：
後手：
手数----指手---------消費時間--
```
We utilize _手合割_ header tag, that is in standard shogi used for handicap names. This is not something I made up, but it seems to be relatively established. So far so good.

But what about custom positions, either handicaps  or completely custom positions? I'm adding handicaps for other variants now, so as an example let's use this handicap for minishogi: 飛車落ち (rook down). Currently we would display it as follows:

```
後手の持駒：なし
  ５ ４ ３ ２ １
+---------------+
| ・v角v銀v金v玉|一
| ・ ・ ・ ・v歩|二
| ・ ・ ・ ・ ・|三
| 歩 ・ ・ ・ ・|四
| 玉 金 銀 角 飛|五
+---------------+
先手の持駒：なし
後手番
先手：
後手：
手数----指手---------消費時間--
```

There are few _issues_ with this.

1. We are not indicating it's minishogi, should we use `手合割：5五将棋`?
2. If we use `手合割：5五将棋`, we can't indicate the handicap with _飛車落ち_, since _手合割_ is already used for minishogi. So I guess we have to display the whole board as it's above, prob no way around it
3. Sente/gote should be shitate/uwate (in kanji obv)

This doesn't apply to chushogi, for chushogi we don't display any _手合割_, which is what I saw mostly in the wild.

**Comment by ddugovic** [comment]
> I'm adding handicaps for other variants now...

I'm trying to get https://github.com/TheYoBots/Lishogi-Bot.git to be able to play as either color in each variant and am trying to figure out irregularities in the existing API (and irregularities in each engine, and in Lishogi-Bot itself).

I'm also seeing that Lishogi has some BOT accounts which evidently can play variants and handicaps somehow, but don't explain how they do it.

I also have #542 and #580 to try to make Lishogi's API more useful... I didn't consider how variant handicaps affect these, but maybe I should close these PRs if they can't be merged due to conflicts with features you are adding?

**Comment by WandererXII** [comment]
KIF is unrelated to bots, kif is used only for exporting/importing games. Bots send all the necessary info here: https://github.com/WandererXII/lishogi/blob/master/modules/bot/src/main/BotJsonView.scala#L27
Your bot needs to accept the variant (config), then in `initialSfen` you should be able to read the initial color.

Those PRs look good, I will merge them before the next update, sorry about the delay.
