### ISSUE TITLE
Sennichite game end bug

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#688]
https://lishogi.org/forum/lishogi-feedback/zPKeBhss

**Comment by WandererXII** [comment]
> **Perpetual Check**
> ...
> It does not matter whether the identical position (i.e. starting point of the recurrence) is the turn of the checking player himself or the other player's.

We consider it perpetual check only if the repetition occurs during the turn of the checking player, which is wrong, so I'm going to fix that. What I'm not sure about tho, is what to do if both players had consecutive checks since the repetition started. Should we call it a draw, or the person who made the last repetition move with check should lose?

**Comment by WandererXII** [comment]
JP wiki says this:
> また、両者が連続王手で千日手となった場合については定義されていないが、いまだ局面や手順として再現できておらず、公式戦でも前例が存在しないがゆえ、特に問題視されていない。

If I understand correctly that situation is not defined, so I'm fine with just calling it a draw?

**Comment by WandererXII** [comment]
https://github.com/WandererXII/scalashogi/commit/d1adf6a9d13b46dbae13d37d0b3dfe45b436c6ea

**Comment by WandererXII** [comment]
Done, should be good now, but please keep an eye out. Thanks for letting me know here:)
