### ISSUE TITLE
Don’t highlight “check” in chu shogi

### ISSUE THREAD

**Issue by Olekaze** [WandererXII/lishogi#690]
check highlights shouldn’t be an option on lishogi.

We had a discussion on discord and these are some of the arguments against highlights

- “Check” doesn’t exist and never existed in chu shogi
- A king under attack is no different from any other piece under attack. Players should be allowed to blunder their kings
- You’re responsible for looking after your pieces and It's a fairly small task to watch over your king. it's the bare minimum
- In chu shogi, you have the ability to play with the intention of tricking your opponent into blundering their king. This is impossible with check highlights
- Chu shogi is already a reasonably inaccessible game and not highlighting check doesn't make it any less accessible

**Comment by daxx00** [comment]
I agree with this. The highlights are fine for chess or modern shogi, since you have no choice but to get out of check. But in chu shogi, there is no such obligation, so it's basically a "your piece is attacked" hint. This would never be acceptable in chess or modern shogi for something like a rook or queen under attack. So why here?

**Comment by WandererXII** [comment]
I mostly agree, so I will change it.
