### ISSUE TITLE
Board pieces and hand pieces

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#694]
It always bothered me, that the pieces in hand for variants such as minishogi are much smaller that the pieces on board. What I mean:
![minicur](https://github.com/WandererXII/lishogi/assets/43043181/f5914bd6-98d8-4aad-acba-b0a0784fa53e)

The obvious solution is to just make them bigger:
![minialt2](https://github.com/WandererXII/lishogi/assets/43043181/c6831eb0-d2b0-4805-a3d4-bee6805fd91e)

The issue there is that it pushes the side tables away and takes more screen that the default layout. I don't want the space that's occupied by the board and pieces to change across variants (that's why I'm keeping the gaps with chushogi).

Another solution:
![minialt](https://github.com/WandererXII/lishogi/assets/43043181/8fba04eb-b1b6-4d8a-b879-7ba32aaaa165)

Something like that... I honestly always find that the small variants are too close and big anyways and I tend to make the board smaller while playing, so I'm not completely against something like this, but this is probably too much, but idk...

**Comment by CouchTomato87** [comment]
My 2 cents is that it doesn't bother me too much. The board in these small variants is already blown up -- the ones on the side are really the "normal" ones. 

I was also going to add another topic, but since this falls under the general topic of "hand pieces," Karolina had this comment on the Discord:

![image](https://github.com/WandererXII/lishogi/assets/52322435/f9eebb35-34e0-4f6e-9b3c-8079cfc5da42)

When you have a light background (such as the one she uses), this can often obscure the pieces in hand. Ideally, the pieces should be visible no matter what you choose. In the original mode with the hands being on the right side of the screen, they had the background of the board. Can we bring back the board background for these pieces? Maybe give them a nice little border like the ones that surrounds the board for coordinates to make it look nice

**Comment by WandererXII** [comment]
> My 2 cents is that it doesn't bother me too much. The board in these small variants is already blown up -- the ones on the side are really the "normal" ones.

The board is really uncomfortably large... Not sure what's the best way to resolve that.

> I was also going to add another topic, but since this falls under the general topic of "hand pieces," Karolina had this comment on the Discord:
> 
> When you have a light background (such as the one she uses), this can often obscure the pieces in hand. Ideally, the pieces should be visible no matter what you choose. In the original mode with the hands being on the right side of the screen, they had the background of the board. Can we bring back the board background for these pieces? Maybe give them a nice little border like the ones that surrounds the board for coordinates to make it look nice

Something like this (using thick grid option, so it's more visible)?
![image](https://github.com/WandererXII/lishogi/assets/43043181/cb42a488-e541-4d2d-b538-0e214df57d12)
I would have to add this as another option to preferences, I feel like we already have too many of them, but this is probably justified...

**Comment by CouchTomato87** [comment]
Yeah I think it's necessary. And that looks awesome!

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/1352fc1d419e289114e0f1d3d0d8886a37389671

**Comment by WandererXII** [comment]
I will try this. Keeping the space for the default 9x9 board, but making the board smaller, the issue is the board is not aligned on top or bottom, but I think that's better than the current behavior. 
![image](https://github.com/WandererXII/lishogi/assets/43043181/3ba8aac9-50f5-4d14-97ec-9b7dd6d351d6)
