### ISSUE TITLE
[Variant] Check Shogi

### ISSUE THREAD

**Issue by ch-suginami** [WandererXII/lishogi#712]
I suggest a new variant "王手将棋(Check Shogi)".
This is only one simple rule: When your king is checked, you lose.
This rule is one of a famous rule in Japan as variants.
Thanks.

**Comment by WandererXII** [comment]
All other shogi rules apply? Such as impasse (持将棋), repetition (千日手) and perpetual check?

**Comment by ch-suginami** [comment]
Yes. All other rules except perpetual check are applied.
Perpetual check never happens because one check wins the game.
The other rules are perhaps needed but such situations are very low possibilities.

**Comment by WandererXII** [comment]
Just to make sure - delivering check by dropping pawn is allowed. Asking because of 打ち歩詰め in honshogi, so I was wondering whether checkshogi doesn't have something similar.

**Comment by WandererXII** [comment]
But 王手 with dropped pawn is allowed... So I was wondering about these two case scenarios:

- Dropping a pawn in front of the opponent's king delivering check (NOT checkmate) and winning - OK?
- Dropping a pawn in front of the opponent's king delivering check AND checkmate (which has no impact on the outcome of the game) and winning  - NOT OK?

Since checkmate is not the objective of the game, I think it would be more reasonable to either allow 打ち歩詰め, or not allow checking with dropped pawns at all. I tried looking around and couldn't find much, what do you think?

**Comment by ch-suginami** [comment]
> Dropping a pawn in front of the opponent's king delivering check (NOT checkmate) and winning - OK?
> Dropping a pawn in front of the opponent's king delivering check AND checkmate (which has no impact on the outcome of the game) and winning - NOT OK?
Yes.

If I would choose either, I will choose former one(allow 打ち歩詰め) because dropping a pawn with check is needed to allow.
打ち歩詰め is very rare case in checkshogi so 打ち歩詰め can be allowed if it is easier to make.
