### ISSUE TITLE
make it easier to get on the leaderboard for variants 

### ISSUE THREAD

**Issue by Olekaze** [WandererXII/lishogi#724]
The leaderboards for variants are empty. for standard shogi you need a rating deviation on 75 or less to get on the leaderboard but for variants it's 65. this makes it very hard to get on the leaderboard for variants like chu shogi where it's hard to find a game. for example, https://lishogi.org/@/shibamizo57 always has a game seek up and gets a couple games a day but his rating deviation barely changes, and I remember having over 70 ongoing correspondence games but my rating deviation was still rising. the strongest and most active players like shibamizo, dax00, foxon1k, minase, etc. aren't on the leaderboard because It's hard to play enough games quickly. I would raise it to 75 or higher

**Comment by M-DinhHoangViet** [comment]
I angree it

**Comment by TheYoBots** [comment]
I think for variants like chu shogi a rating deviation of 85 makes sense to be on the leaderboard, for annan shogi it should be 75 and for other variants 65 makes sense since they are much smaller board and significantly simpler than shogi.

**Comment by WandererXII** [comment]
Agreed, I will tweak it. We could maybe start even higher and lower it later if needed.

**Comment by M-DinhHoangViet** [comment]
I think this PR can solve

**Comment by TheYoBots** [comment]
What about: 
standard: 75
Chu Shogi: 85
Annan shogi: 75
Other variants: 65

Like I mentioned earlier.

**Comment by M-DinhHoangViet** [comment]
@TheYoBots According to my PR:
Standard 75 -> 85
Variants 65 -> 75
We can change it if it doesn't make reasonable. And of course @WandererXII's final decision

**Comment by TheYoBots** [comment]
> What about:
> standard: 75
> Chu Shogi: 85
> Annan shogi: 75
> Other variants: 65
> 
> Like I mentioned earlier.

The only reason I mentioned this is becuase:
1. having a high rd and being on a kytoshogi or minishogi leaderboard makes no sense since these variants have small boards and are significantly easier than other variants.
2. Standard could have the same rd as the leaderboard is quite filled already and 75 seems like a standard number for reference.
3. Annan shogi has the exact same board size as standard shogi and the rule differences aren't major. So if this was a variant on lichess it would have a rd less than 65 (like all variants on lichess whether they are more complicated than standard chess or not). I think that should be changed to 75 because there aren't many that play annan shogi making it extremely for new players to get into the leaderboard.
4. Chu shogi is an extremely complex game. One *"short"* game itself could take 7-8 hours to complete (with proper play and no resignation). So getting an rd below 65 is practically impossible especially considering the fact that there aren't that many chu shogi players. Hence the number 85 (Higher than even standard shogi due to game complexity).

I hope the above details provides reasonable information as to why I mentioned a change to the PR. :)

**Comment by Olekaze** [comment]
By the way, I've seen multiple people grinding for chu shogi rating with 1+0 games. Could you do something like lichess and only allow rated games above a certain time control like 5 mins? (on lichess you can't create rated 1/4+0 variant games)

**Comment by TheYoBots** [comment]
> By the way, I've seen multiple people grinding for chu shogi rating with 1+0 games. Could you do something like lichess and only allow rated games above a certain time control like 5 mins? (on lichess you can't create rated 1/4+0 variant games)

I don't think this makes sense in kyoto and minishogi right?

**Comment by Olekaze** [comment]
yes just for chu shogi

**Comment by M-DinhHoangViet** [comment]
Ok, pls reset sever
