### ISSUE TITLE
Impasse positions break the engine

### ISSUE THREAD

**Issue by KatsuyamaE** [WandererXII/lishogi#781]
**Exact URL where the bug happened**
https://lishogi.org/analysis/standard/
**Steps to reproduce the bug**
Paste the SFEN `+R8/2+NK1+R+P+P1/+P+PPS+P4/6g+b1/7p1/3g5/3+b1g+p1+p/5p3/5k+p2 b G3S3N3L7Pl 1` into the SFEN box. and turn on the engine.
**What did you expect to happen?**
The engine giving normal evaluations.
**What happened instead?**
The engine gives a `#2` evaluation with no next moves given.
**Operating system and browser version**
Windows 11 64-bit, Chrome 121.0.6167.86

![image](https://github.com/WandererXII/lishogi/assets/61017474/1192fb7b-900f-4aae-b344-cad32b2a0862)

**Comment by WandererXII** [comment]
Nice find, thanks for reporting this. The issue seems to be caused by engine returning 'bestmove win' to declare win by impasse and we are not handling that.
I can either turn off `EnteringKingRule` or somehow signal the win by impasse, probably by disabling the engine like when checkmate occurs. I'm more inclined to do the former - to not consider impasse in evaluation, since in analysis we allow the play to continue even after impasse.

**Comment by KatsuyamaE** [comment]
First option seems the most reasonable to me
